### PR TITLE
Add ini setting to skip intros

### PR DESCRIPTION
**Pull request by jefetienne**
For players wanting to skip the intros entirely, they can set "skip_intros" in the .ini file to '1'.

### CODE REVIEW

**Comment by nextghost** [comment]
It'd be best to add a checkbox for this setting into the main options window and flip the value ("Play intro on startup", default = 1).

**Comment by jefetienne** [comment]
That's fine. My initial reasoning was because the options window only appears in-game, that the options inside it would only be ones impacting the gameplay itself. But I am definitely okay with adding that if you still would like it.

**Comment by jefetienne** [comment]
I have added the checkbox anyway and flipped the value to 'play_intros', default 1. It is ready to merge.

**Comment by nextghost** [comment]
Thanks, but this is not a gameplay change so the checkbox should go to `SetOptions()` instead. It's right under `configure_features()` is signus.cpp.

**Comment by jefetienne** [comment]
Ah, my apologies. I put it beneath the "full screen" checkbox.

**Comment by nextghost** [comment]
Thanks, squashed and merged.

**Pull request merged**
